# -*- coding: utf-8 -*-
"""
merge_lexicon.py — OFFLINE (not shipped).

Combines the workflow-generated, niqqud-vocalized lexicon
(tools/generated_lexicon.json) with the frozen hand-verified seed
(tools/words_seed.py) and writes tools/words.py for the build to consume.

Policy:
  - Vocabulary + niqqud come from the generated lexicon (all forms vocalized).
  - For nouns that exist in BOTH, the seed's hand-verified gender/number wins
    (and any disagreement is reported — a free cross-check on the generator).
  - Words only in the seed are reported (not auto-added, to keep every shown
    word vocalized); fill them back in with niqqud if coverage needs them.

Run:  python3 tools/merge_lexicon.py   then   python3 tools/build_lexicon.py
"""

import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import words_seed as S  # noqa: E402

NIQQUD = re.compile(r"[֑-ׇ]")
HEB = re.compile(r"[א-ת]")


def strip(s):
    return NIQQUD.sub("", s)


def slen(s):
    return len(HEB.findall(strip(s)))


import glob  # noqa: E402
gen = {"nouns": [], "adjectives": [], "verbs": []}
for path in sorted(glob.glob(os.path.join(HERE, "generated_lexicon*.json"))):
    d = json.load(open(path, encoding="utf-8"))
    for k in gen:
        gen[k].extend(d.get(k, []))
print(f"loaded {gen and sum(len(v) for v in gen.values())} raw entries from generated_lexicon*.json")

# ---- nouns ----
nouns = {}  # stripped -> [w, g, n]
for e in gen["nouns"]:
    k = strip(e["w"])
    if slen(e["w"]) >= 2 and k not in nouns:
        nouns[k] = [e["w"], e["g"], e["n"]]

discrepancies, seed_only_nouns = [], []
for (w, g, n) in S.NOUNS:
    k = strip(w)
    if k in nouns:
        if nouns[k][1] != g:
            discrepancies.append(f"{k}: generated={nouns[k][1]} seed={g}  (kept seed)")
            nouns[k][1] = g
            nouns[k][2] = n
    else:
        seed_only_nouns.append(w)

# ---- adjectives (vocalized 4-form from generated) ----
adjectives = {}
for e in gen["adjectives"]:
    k = strip(e["ms"])
    if slen(e["ms"]) >= 2 and k not in adjectives:
        adjectives[k] = [e["ms"], e["fs"], e["mp"], e["fp"]]
seed_only_adj = [a[0] for a in S.ADJECTIVES if strip(a[0]) not in adjectives]

# ---- verbs ----
verbs = {}
for e in gen["verbs"]:
    k = strip(e["ms"])
    if slen(e["ms"]) >= 2 and k not in verbs:
        verbs[k] = [e["ms"], e["fs"], e["mp"], e["fp"], bool(e["trans"])]
seed_only_verbs = [v[0] for v in S.VERBS if strip(v[0]) not in verbs]

# ---- hand-curated gap-fill (generated entries win; these only fill gaps) ----
try:
    import words_extra as X
    for (w, g, n) in X.EXTRA_NOUNS:
        nouns.setdefault(strip(w), [w, g, n])
    for forms in X.EXTRA_ADJECTIVES:
        adjectives.setdefault(strip(forms[0]), list(forms))
    for row in X.EXTRA_VERBS:
        verbs.setdefault(strip(row[0]), [row[0], row[1], row[2], row[3], bool(row[4])])
except ImportError:
    pass


# ---- write words.py ----
def q(s):
    return '"' + s + '"'


lines = [
    "# -*- coding: utf-8 -*-",
    '"""AUTO-GENERATED by tools/merge_lexicon.py — do not hand-edit.',
    "Sources: tools/words_seed.py (verified genders) + tools/generated_lexicon.json (niqqud).",
    "All forms are vocalized (menukad). Re-run merge_lexicon.py to regenerate.",
    '"""',
    "",
    "NOUNS = [",
]
for k, (w, g, n) in nouns.items():
    lines.append(f"    ({q(w)}, {q(g)}, {q(n)}),")
lines += ["]", "", "ADJECTIVES = ["]
for k, (ms, fs, mp, fp) in adjectives.items():
    lines.append(f"    ({q(ms)}, {q(fs)}, {q(mp)}, {q(fp)}),")
lines += ["]", "", "VERBS = ["]
for k, (ms, fs, mp, fp, tr) in verbs.items():
    lines.append(f"    ({q(ms)}, {q(fs)}, {q(mp)}, {q(fp)}, {tr}),")
lines += ["]", ""]

with open(os.path.join(HERE, "words.py"), "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

print("wrote tools/words.py")
print(f"  nouns={len(nouns)}  adjectives={len(adjectives)}  verbs={len(verbs)}")
print(f"\ngender disagreements (seed kept): {len(discrepancies)}")
for d in discrepancies:
    print("   -", d)
print(f"\nseed-only words NOT carried over (unvocalized; add niqqud if coverage needs them):")
print("   nouns:", " ".join(seed_only_nouns) or "(none)")
print("   adjectives:", " ".join(seed_only_adj) or "(none)")
print("   verbs:", " ".join(seed_only_verbs) or "(none)")
